(defun pythagorean-triple-with-sum (sum)
  (labels ((ptws (m n)
    (if (and (and (< m sum) (< n (- sum 1))) (> m n))
      (let ((a (- (* m m) (* n n)))
            (b (* 2 m n))
            (c (+ (* m m) (* n n))))
        (if (and (= (+ a b c) sum) (= (+ (* a a) (* b b)) (* c c)))
          (list a b c)
          (ptws m (+ n 1))))
      (if (and (< m sum) (< n (- sum 1)))
        (ptws (+ m 1) 1)
        '()))))
    (ptws 2 1)))

(print (apply '* (pythagorean-triple-with-sum 1000)))
